// ======================
// BASE URL (FINAL)
// ======================
const BASE_URL =
  localStorage.getItem("DHAMANPAY_API_BASE") ||
  "https://dhamanpay.onrender.com/api";

let currentMerchant = null;
let orders = [];
let selectedCustomer = null;

if (!getToken()) {
  window.location.href = 'login.html';
}

// ======================
// HELPERS
// ======================
function setText(id, value) {
  const el = document.getElementById(id);
  if (el) el.textContent = value ?? '—';
}

function formatMoney(value) {
  return `${Number(value || 0).toLocaleString()} DZD`;
}

// ======================
// MESSAGES
// ======================
function showFormMessage(text, success = false) {
  const box = document.getElementById('formMessage');
  if (!box) return;

  box.className = 'rounded-2xl p-4 text-sm';
  box.classList.add(success ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700');
  box.textContent = text;
}

function showSearchMessage(text, success = false) {
  const box = document.getElementById('customerSearchMessage');
  if (!box) return;

  box.className = 'mt-3 rounded-2xl p-3 text-sm';
  box.classList.add(success ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700');
  box.textContent = text;
}

// ======================
// LOAD PROFILE
// ======================
async function loadMeData() {
  try {
    const res = await getMe();
    currentMerchant = res.data || {};

    console.log('MERCHANT DATA:', currentMerchant);

    setText('heroStoreName', currentMerchant.store_name);
    setText('heroMerchantName', currentMerchant.full_name);

    setText('merchantName', currentMerchant.full_name);
    setText('merchantRole', currentMerchant.role?.toUpperCase());
    setText('merchantStoreName', currentMerchant.store_name);
    setText('merchantEmail', currentMerchant.email);
    setText('merchantPhone', currentMerchant.phone);
    setText('merchantId', currentMerchant.id);
    setText('merchantCommercialRegister', currentMerchant.commercial_register);

    setText('merchantStoreNameCard', currentMerchant.store_name);
    setText('merchantCommercialRegisterCard', currentMerchant.commercial_register);
  } catch (err) {
    console.error(err);
    window.location.href = 'login.html';
  }
}

// ======================
// CUSTOMER SEARCH
// ======================
async function searchCustomerUI() {
  const name = document.getElementById('customerSearchName').value.trim();
  const phone = document.getElementById('customerSearchPhone').value.trim();

  if (!name && !phone) {
    showSearchMessage('Enter name or phone.');
    return;
  }

  try {
    const res = await searchCustomers(name, phone);
    const customers = res.data || [];

    const box = document.getElementById('customerSearchResults');
    box.innerHTML = '';

    if (!customers.length) {
      showSearchMessage('No customer found');
      return;
    }

    showSearchMessage('Customers found', true);

    customers.forEach(c => {
      const btn = document.createElement('button');
      btn.className = 'w-full text-left p-4 border rounded-xl hover:bg-blue-50';
      btn.innerHTML = `
        <b>${c.full_name}</b><br>
        ${c.phone} <br>
        ID: ${c.id}
      `;

      btn.onclick = () => {
        selectedCustomer = c;
        const input = document.getElementById('customerId');
        input.value = `${c.full_name} (#${c.id})`;
        input.dataset.customerId = c.id;
      };

      box.appendChild(btn);
    });

  } catch (err) {
    showSearchMessage(err.message);
  }
}

// ======================
// CREATE ORDER (IMPORTANT FIX)
// ======================
async function createOrderUI(e) {
  e.preventDefault();

  const customerId = document.getElementById('customerId').dataset.customerId;
  const amount = Number(document.getElementById('amount').value);
  const address = document.getElementById('deliveryAddress').value.trim();
  const product = document.getElementById('productName').value.trim();
  const serial = document.getElementById('expectedSerialNumber').value.trim();

  if (!customerId) return showFormMessage('Select customer first');
  if (!amount) return showFormMessage('Enter amount');
  if (!address || !product || !serial) return showFormMessage('Fill all fields');

  try {
    const res = await createOrder({
      customer_id: Number(customerId),
      amount,
      delivery_address: address,
      product_name: product,
      expected_serial_number: serial
    });

    showFormMessage('Order created successfully (code generated by backend)', true);

    document.getElementById('createOrderForm').reset();
    document.getElementById('customerId').dataset.customerId = '';

    await loadOrders();

  } catch (err) {
    showFormMessage(err.message);
  }
}

// ======================
// ORDERS
// ======================
function normalizeOrder(o) {
  return {
    id: o.id,
    code: o.order_code || o.code,
    customer: o.customer?.full_name || `#${o.customer_id}`,
    amount: o.amount,
    status: o.status,
    product: o.product_name,
    serial: o.expected_serial_number,
    address: o.delivery_address
  };
}

function renderOrders() {
  const box = document.getElementById('ordersList');
  box.innerHTML = '';

  orders.forEach(o => {
    const card = document.createElement('div');
    card.className = 'p-4 border rounded-xl';

    card.innerHTML = `
      <b>${o.code}</b><br>
      ${o.customer}<br>
      ${o.product}<br>
      ${o.serial}<br>
      ${o.address}<br>
      ${formatMoney(o.amount)}<br>
      ${o.status}
    `;

    box.appendChild(card);
  });
}

async function loadOrders() {
  const res = await getOrders();
  orders = (res.data || []).map(normalizeOrder);
  renderOrders();
}

// ======================
// LOGOUT
// ======================
async function logoutUI() {
  clearToken();
  window.location.href = 'login.html';
}

// ======================
// INIT
// ======================
document.addEventListener('DOMContentLoaded', async () => {
  await loadMeData();
  await loadOrders();

  document.getElementById('searchCustomerBtn').onclick = searchCustomerUI;
  document.getElementById('createOrderForm').onsubmit = createOrderUI;
  document.getElementById('logoutBtn').onclick = logoutUI;
});